sudo: false
language: emacs-lisp
cache:
  - directories:
      - $HOME/emacs/
addons:
  apt:
    packages:
      - gnutls-bin
      - gnupg2
env:
  global:
    - PATH=$HOME/local/bin:$HOME/local/evm/bin:$PATH
  matrix:
    - EVM_EMACS=emacs-26.1-travis-linux-xenial
    - EVM_EMACS=emacs-26.2-travis-linux-xenial
    - EVM_EMACS=emacs-26.3-travis-linux-xenial
    - EVM_EMACS=emacs-27.1-travis-linux-xenial
    - EVM_EMACS=emacs-git-snapshot-travis-linux-xenial
before_script:
  - sh .travis-ci/install-evm.sh $EVM_EMACS
script:
  - emacs --version
  - make EMACS=emacs
  - make clean
  - make distclean
